config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  
  resources :tasks
  resources :histories
  resources :projects
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :history
  
  validates :history, presence: true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:description, :history_id, :done)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for @task, :html => { :class => "form-horizontal task" } do |f| %>

  <% if @task.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>
  <div class="form-group">
    <%= f.label :history_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :history_id, :class => 'form-control' %>
    </div>
    <%=f.error_span(:history_id) %>
  </div>
  <div class="form-group">
    <%= f.label :done, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :done, :class => 'form-control' %>
    </div>
    <%=f.error_span(:done) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                tasks_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/tasks/edit.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tasks/index.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:history_id) %></th>
      <th><%= model_class.human_attribute_name(:done) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to task.id, task_path(task) %></td>
        <td><%= task.description %></td>
        <td><%= task.history_id %></td>
        <td><%= task.done %></td>
        <td><%=l task.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      task_path(task), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_task_path(task), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      task_path(task),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_task_path,
            :class => 'btn btn-primary' %>

app/views/tasks/new.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tasks/show.html.erb
<%- model_class = Task -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @task.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:history_id) %>:</strong></dt>
  <dd><%= @task.history_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:done) %>:</strong></dt>
  <dd><%= @task.done %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              tasks_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_task_path(@task), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              task_path(@task),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>