config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  
  resources :tasks
  resources :histories
  resources :projects
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :project
  belongs_to :person
  has_many :tasks

  accepts_nested_attributes_for :tasks, :allow_destroy => true,
                        :reject_if => proc { |attributes| attributes['description'].blank? }
  
  validates :name, presence: true
  validates :status, presence: true
  validates :person, presence: true
  validate :validationDate

  validates_format_of :points, :with => /1[3]|[1,2,3,5,8]$|/

  
	def validationDate
		if self.finished_at < self.started_at
			errors.add(:finished_at, "menor que a Data de Início")
		end 
   
    end
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :set_history, only: [:show, :edit, :update, :destroy]
  before_action :set_person, only:  [:create, :edit, :update, :new]
  before_action :set_project, only:  [:create, :edit, :update, :new]
  # GET /histories
  # GET /histories.json
  def index
    @histories = History.all
  end

  # GET /histories/1
  # GET /histories/1.json
  def show
  end

  # GET /histories/new
  def new
    @history = History.new
    @history.tasks.build()
  end

  # GET /histories/1/edit
  def edit
     @history.tasks.build()
  end

  # POST /histories
  # POST /histories.json
  def create
    @history = History.new(history_params)

    respond_to do |format|
      if @history.save
        format.html { redirect_to @history, notice: 'History was successfully created.' }
        format.json { render :show, status: :created, location: @history }
      else
        format.html { render :new }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /histories/1
  # PATCH/PUT /histories/1.json
  def update
    respond_to do |format|
      if @history.update(history_params)
        format.html { redirect_to @history, notice: 'History was successfully updated.' }
        format.json { render :show, status: :ok, location: @history }
      else
        format.html { render :edit }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /histories/1
  # DELETE /histories/1.json
  def destroy
    @history.destroy
    respond_to do |format|
      format.html { redirect_to histories_url, notice: 'History was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_history
      @history = History.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def history_params
      params.require(:history).permit(:name, :project_id, :status, :person_id, :description, :started_at, :finished_at, :deadline, :points, :tasks_attributes => [:id, :description, :done, :_destroy])
    end

    def set_person
      @people = Person.all
    end 

    def set_project
      @projects = Project.all
    end  
end

app/helpers/histories_helper.rb
module HistoriesHelper

end

app/views/histories/_form.html.erb
<%= form_for @history, :html => { :class => "form-horizontal history" } do |f| %>

  <% if @history.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@history.errors.count, "error") %> prohibited this history from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @history.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :project_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.collection_select(:project_id, @projects, :id, :name, prompt: false) %>
    </div>
    <%=f.error_span(:project_id) %>
  </div>
  <div class="form-group">
    <%= f.label :status, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select(:status, 
                options_for_select([["Pendente", "P"], ["Em Andamento", "A"], ["Concluído", "C"], ["Entregue", "E"]], @history.status),
                { include_blank: false }) %>
    </div>
    <%=f.error_span(:status) %>
  </div>
  <div class="form-group">
    <%= f.label :person_id, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.collection_select(:person_id, @people, :id, :name, prompt: false) %>
    </div>
    <%=f.error_span(:person_id) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>
  <div class="form-group">
    <%= f.label :started_at, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.date_select(:started_at) %>
    </div>
    <%=f.error_span(:started_at) %>
  </div>
  <div class="form-group">
    <%= f.label :finished_at, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.date_select(:finished_at) %>
    </div>
    <%=f.error_span(:finished_at) %>
  </div>
  <div class="form-group">
    <%= f.label :deadline, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.date_select(:deadline) %>
    </div>
    <%=f.error_span(:deadline) %>
  </div>
  <div class="form-group">
    <%= f.label :points, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :points, :class => 'form-control' %>
    </div>
    <%=f.error_span(:points) %>
  </div>

  <h2>Tarefas</h2>
  <table class="table table-striped">
    
    <%= f.fields_for :tasks do |ff| %>
      <tr>
        <td>
          <%= ff.label :description %> 
          <%= ff.text_field :description %>
        </td>
        <td>
          <%= ff.label :done %>
          <%= ff.check_box(:done, {}, "Feito") %>
        </td>
        <td>
          <%= ff.hidden_field :id %>
        </td>
        <td>
          <%= ff.label :_destroy, "Apagar" %>
          <%= ff.check_box :_destroy %>
        <td>
      </tr>
    <% end %>
  </table>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                histories_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/histories/edit.html.erb
<%- model_class = History -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/histories/index.html.erb
<%- model_class = History -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:project_id) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:person_id) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:started_at) %></th>
      <th><%= model_class.human_attribute_name(:finished_at) %></th>
      <th><%= model_class.human_attribute_name(:deadline) %></th>
      <th><%= model_class.human_attribute_name(:points) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @histories.each do |history| %>
      <tr>
        <td><%= link_to history.id, history_path(history) %></td>
        <td><%= history.name %></td>
        <td><%= history.project.name %></td>
        <td><%= history.status %></td>
        <td><%= history.person.name %></td>
        <td><%= history.description %></td>
        <td><%= history.started_at %></td>
        <td><%= history.finished_at %></td>
        <td><%= history.deadline %></td>
        <td><%= history.points %></td>
        <td><%=l history.created_at %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      history_path(history), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_history_path(history), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      history_path(history),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>



<%= link_to t('.new', :default => t("helpers.links.new")),
            new_history_path,
            :class => 'btn btn-primary' %>

app/views/histories/new.html.erb
<%- model_class = History -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/histories/show.html.erb
<%- model_class = History -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @history.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:project_id) %>:</strong></dt>
  <dd><%= @history.project.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @history.status %></dd>
  <dt><strong><%= model_class.human_attribute_name(:person_id) %>:</strong></dt>
  <dd><%= @history.person.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @history.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:started_at) %>:</strong></dt>
  <dd><%= @history.started_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:finished_at) %>:</strong></dt>
  <dd><%= @history.finished_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:deadline) %>:</strong></dt>
  <dd><%= @history.deadline %></dd>
  <dt><strong><%= model_class.human_attribute_name(:points) %>:</strong></dt>
  <dd><%= @history.points %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              histories_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_history_path(@history), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              history_path(@history),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>